version: "3"

services:
  magenta:
    build:  ./magenta
    container_name: magenta
    tty: true
    volumes:
      - $PWD/workdir:/magenta-data/
    ports:
      - 6006:6006
      
  timidity:
    build: ./timidity-ubuntu
    container_name: timidity
    tty: true
    volumes:
      - $PWD/workdir:/wavfile
